name: Playwright CI

on:
  push:
    branches: [ main, remote ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Install Playwright Browsers with Dependencies
        run: |
          mvn exec:java \
          -Dexec.mainClass=com.microsoft.playwright.CLI \
          -Dexec.classpathScope=test \
          -Dexec.args="install --with-deps"

      - name: Run Tests
        run: mvn test -e -Dheadless=true

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: |
            target/surefire-reports/
            target/allure-results/
            allure-results/
